[package]
name = "focusvent"
version = "0.1.0"
authors = ["werner <werner@yahoo.es>"]

[dependencies]
rocket = "0.3.16"
rocket_codegen = "0.3.16"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]